
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$python\
$character"""

[directory]
style = "#63b8fa"
home_symbol = "󰋜 ~"

[character]
success_symbol = "[❯](#50fa7b)"
error_symbol = "[❯](#F04141)"
vimcmd_symbol = "[❮](purple)"

[git_branch]
format = "[$branch]($style)"
style = "#AEB0B0"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "blue"
conflicted = "󰞇"
untracked = ""
modified = ""
staged = "󰏗"
renamed = ""
deleted = "󰧧"
stashed = "≡"

[git_status.conflicted]
style = "#f79169"

[git_status.untracked]
style = "red"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
